version: "3.9"

services:
  db:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=buurbak
      - POSTGRES_PASSWORD=buurbak
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U buurbak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: buurbak-api
    container_name: buurbak-api
    build:
      context: api
    ports:
      - "3080:3080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_USERNAME: buurbak
      DATABASE_PASSWORD: buurbak
      DATABASE_HOST: db
      MAIL_HOST: maildev
      JWT_SECRET: secret

  maildev:
    image: maildev/maildev
    container_name: buurbak-maildev
    ports: 
      - "1080:1080"
