version: "3.9"

services:
  traefik:
    image: traefik:v2.4
    container_name: your-monthly-playlist-traefik-dev
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=buurbak
      - POSTGRES_PASSWORD=buurbak
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U buurbak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: buurbak-api
    container_name: api
    build:
      context: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/buurbak
      - SPRING_DATASOURCE_USERNAME=buurbak
      - SPRING_DATASOURCE_PASSWORD=buurbak
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    labels: 
      traefik.enable: true
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api/v1`)
      traefik.http.services.backend.loadbalancer.server.port: 3080
      # traefik.http.middlewares.backendpathstrip.stripprefix.prefixes: /api/v1
      # traefik.http.routers.backend.middlewares: backendpathstrip@docker
    
  frontend:
    image: buurbak-frontend
    build:
      context: frontend
    container_name: frontend
    labels: 
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`localhost`)
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.services.frontend.loadbalancer.server.port: 80
      


