version: '3.9'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: buurbak
      POSTGRES_USER: buurbak
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U buurbak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    labels: 
      traefik.enable: true
      traefik.http.routers.maildev.rule: Host(`mail.localhost`)
      traefik.http.services.maildev.loadbalancer.server.port: 1080

  adminer:
    image: adminer
    restart: always
    labels: 
      traefik.enable: true
      traefik.http.routers.adminer.rule: Host(`adminer.localhost`)
      traefik.http.services.adminer.loadbalancer.server.port: 8080
