server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
  port: 80

web:
  cors:
    allowed-origins: "https://www.buurbak.nl"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "*"
    exposed-headers: "*"


gcp:
  auth-file: gcp-account-file.json
  project-id: celestial-sonar-365614
  bucket-id: buurbak_public
  dir-name: prod


spring:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:postgresql://${DATABASE_HOST}:5432/buurbak

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  mail:
    host: ${MAIL_HOST}
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
