server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
  port: 3080

web:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "*"
    exposed-headers: "*"

gcp:
  auth-file: gcp-account-file.json
  project-id: celestial-sonar-365614
  bucket-id: buurbak_public
  dir-name: dev

spring:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  datasource:
    username: buurbak
    password: buurbak
    url: jdbc:postgresql://localhost:5432/buurbak

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
