server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
  port: ${PORT}

jwt:
  token-validity: 18000
  authorities-key: roles
  token-prefix: Bearer
  header-string: Authorization

gcp:
  bucket-id: ${GCP_BUCKET_ID}
  dir-name: ${GCP_BUCKET_DIR_NAME}
  project-id: ${GCP_PROJECT_ID}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
