database: postgresql

data:
  generate-random-data: false

gcp:
  auth-file: ${sm://GCP_AUTH_FILE}

jwt-secret: ${sm://JWT_SECRET}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      initializationFailTimeout: 30000
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      connection-timeout: 20000
      max-lifetime: 1000

  cloud:
    gcp:
      sql:
        instance-connection-name: ${INSTANCE_CONNECTION_NAME}
        database-name: ${DATABASE_NAME}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: false

  mail:
    host: smtp.google.com
    username: ${MAIL_USERNAME}
    password: ${sm://MAIL_PASSWORD}
    port: 587

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true