name: Deploy to Cloud Run & Firebase on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    name: Firebase Deployment frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build frontend
        working-directory: ./frontend
        run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CELESTIAL_SONAR_365614 }}'
          channelId: live
          projectId: celestial-sonar-365614

  build_and_deploy_api:
    name: Cloud Run Deployment api
    runs-on: ubuntu-latest  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Deploy api
      - name: Build buurbak-api
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/buurbak-api:latest api

      - name: Push buurbak-api
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/buurbak-api:latest

      - name: Deploy buurbak-api
        run: |
          gcloud run deploy buurbak-api \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/buurbak-api \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --max-instances 2 \
          --port 80
