name: Build and testing of API

on:
  pull_request:
    branches:
      - main
      - dev

env:
  DATABASE_HOST: localhost
  DATABASE_NAME: buurbak
  DATABASE_PASSWORD: buurbak
  DATABASE_USERNAME: buurbak
  GCP_AUTH_FILE: '{   "type": "service_account",   "project_id": "celestial-sonar-365614",   "private_key_id": "07826abf6f70fb576101240a6fe06d9c4500dc89",   "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCN7rfi0rGwAClZ\naDJpnadcGzrvbTduxFNQOUdPrJ1oJ/KghyrJx0umZJiBS1UDEziYCCfGgrypHBJ1\nbCs4HHYifBWVy/QJtFHoNtzNixHu5CgicEfN0gxj3g3YLCCOmxVPa0+jvuvu3YWN\n1tQop7IOez7TuY24FLvw2M9t9dA4V3DFa4dij4u8q7IfOwmiICFWgU/BkKuVn0Sq\nrRxYDs3GdEYJvAL4MjJAbNMA9K4FYwes6DuM7MgeHaHdUNwTcjMKvLbws06LRuvL\nA6QLOtJErAb+M/P8dGy+tsHw0MhKuVO+rHpeyLHcW5ohI/TtQzh79A61sX6nj8vF\nhawRgAihAgMBAAECggEAIeX8dEeXGa6IMarhs3jsYmK8ijefEC0CqvvrLLvQ4nH8\nEFwIG6YmSsjm5aZ82N2r3B/ChDZwYcFrJTFfBylBC85wB1VtZS30jA4iYVMQRuqm\nLUd81ssOm4GK8/DiG70tc0jxfe3ZArVUswI2rLkUnUHRSRcdonQNSSI3NI+LmhDp\nGs/eCwU+Yi0iQ7QgnLOoJNv0Qv8g7UTwFl3ROJ7j+UxWaa6t7zOJrj8t3RnvA5sz\n6cI4U5KDIY5wRPsXCi2XB5aRO5+AZeUN1uR8R60DGfHRTW3iFn7e+yRiKROvH6ys\n8qBYz030pXE5MyIDVnWSDlTNufnNhs5ONub6DSaR2QKBgQDIawFuiqalxD1V0+Ox\nXmEjFRG1F1pYRGks+CrpwNNs2r2u3/MnUDSRv7UgRID70q2lhHWedpGO7hxJsFFe\ntRBqJyb4A06ALr/QIOTJw/Xz9ZXPTbZt1wwcckiz8wVnXv1pa0eVOi8xWWsZeI41\nybkIF5Ahh56SR+wNf2cku8RN/QKBgQC1S3ETLZs8ti0DpL2VkRf569TGid8e5oMY\nYy3eYw6WmomHRhgOZnSx4jzilCfv1QGGWkvVgg7doUF7+HFc0UJF45VXAM/PS54E\nlHxFVC07BwCkFnZJWxPpt+sorwnYFD2zPIhrbuOK+OlpBxDHev4dUtXW8MQTJmhE\nZk2dtwU0dQKBgEEwdR3EoaIHq7+wFT7LKSNlJgZWWz+cuO00p5iy7NJacBpio8+k\nygSia8LcJWxDwdG1vSBXBs+L6c2aOU1p7bXpmEZRpQYSrrd/C4wJXoYE2r68U1t0\n+G6ESdumb5qJDjps97K1Y0ZVBH4bdX5PaA0WxP3zBAQmusRFLYKIRLjtAoGAYqx7\nEOsjsPmeqnsBzOQ53ocjOiRUUmc4Nw/UKVRU3leiPwRBl6TgIul2JgRpcDnJKK0A\n1WaCXNKl56mjWddzcMKbx8zjTnpjuS5wLPPR4my/RpALNYXi4rR9w5jxjLAHnQR3\nY7HpGvy7XbTAxzIEGUW6qdBFh/7BhWkBGbRBmvkCgYAzEIe8BMuQOdZcrz771tO8\nYmbEPtOgTFVLXfZ5wWBLTdq9R/yRCFL23KMHOn7dC1ugi62jh9nBi7Nb5Hs0EO1O\ntOMeyIJl1Zfhb8PmakMFLNU9W2zYZqOXFEWkoY+j8HLCxiDWfuPID1zMqzBN9SA8\n7FMC+hsbom8A/tnUPCz6qA\=\=\n-----END PRIVATE KEY-----\n",   "client_email": "buurbak-cloud-storage@celestial-sonar-365614.iam.gserviceaccount.com",   "client_id": "101250889797964887376",   "auth_uri": "https://accounts.google.com/o/oauth2/auth",   "token_uri": "https://oauth2.googleapis.com/token",   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/buurbak-cloud-storage%40celestial-sonar-365614.iam.gserviceaccount.com" })'
  GCP_BUCKET_DIR_NAME: dev
  GCP_BUCKET_ID: buurbak_public
  GCP_PROJECT_ID: celestial-sonar-365614
  JWT_SECRET: secret
  MAIL_HOST: localhost
  PORT: 8000
  RANDOM_DATA: true
  SPRING_PROFILES_ACTIVE: dev

jobs:
  build-and-test:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK Temurin 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        run: mvn -f api/pom.xml --batch-mode -DskipTests package

      - name: Test
        run: mvn -f api/pom.xml --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: api/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
