name: Build and testing of API

on:
  pull_request:
    branches:
      - main
      - dev

env:
  DATABASE_HOST: localhost
  DATABASE_NAME: buurbak
  DATABASE_PASSWORD: buurbak
  DATABASE_USERNAME: buurbak
  GCP_BUCKET_DIR_NAME: dev
  GCP_BUCKET_ID: buurbak_public
  GCP_PROJECT_ID: celestial-sonar-365614
  JWT_SECRET: secret
  MAIL_HOST: localhost
  PORT: 8000
  SPRING_PROFILES_ACTIVE: dev

jobs:
  build-and-test:
    name: Build and Test API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK Temurin 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        run: mvn -f api/pom.xml --batch-mode -DskipTests package

      - name: Test
        run: mvn -f api/pom.xml --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: api/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
